import { useState } from "react"
import { ArrowRight, Bot, Check, ChevronDown, Code2, Github, Menu, ShieldCheck, Terminal, X, Zap } from "lucide-react"

const agents = [
  ["Code Agent", "Tạo, refactor và mở rộng module ERP theo chuẩn codebase.", Code2],
  ["Architect Agent", "Biến yêu cầu nghiệp vụ thành SRS, RBD và dependency rõ ràng.", Bot],
  ["Debug Agent", "Đọc log Odoo, traceback và đưa ra hướng sửa có kiểm chứng.", Zap],
  ["Review Agent", "Rà quyền, migration, test và regression trước khi merge.", ShieldCheck],
] as const
const faqs = ["Liodev hỗ trợ phiên bản Odoo nào?", "Liodev có chạy local và self-host không?", "Dữ liệu và API key được xử lý thế nào?", "Liodev khác gì editor AI phổ thông?"]

export default function App() {
  const [open, setOpen] = useState<number | null>(null)
  const [menu, setMenu] = useState(false)
  return <div className="site-shell">
    <header className="nav"><a className="brand" href="#top"><img src="/brand/liodev-logo.svg" alt="Liodev" /></a><button className="menu-toggle" onClick={() => setMenu(!menu)} aria-label="Mở menu">{menu ? <X/> : <Menu/>}</button><nav className={menu ? "nav-links open" : "nav-links"}><a href="#agents">AI Agents</a><a href="#context">Ngữ cảnh ERP</a><a href="#open-source">Open source</a><a href="#faq">FAQ</a><a className="nav-cta" href="https://github.com/itgisgroup/liocode">Xem trên GitHub <ArrowRight size={15}/></a></nav></header>
    <main id="top">
      <section className="hero section-grid"><div className="hero-copy"><div className="eyebrow"><span className="pulse"/> ERPCloud Developer Platform</div><h1>Lập trình ERP nhanh hơn với <em>AI hiểu doanh nghiệp.</em></h1><p>Liodev là code editor và AI Agents dành cho Odoo/ERP — đọc hiểu module, quy trình, dữ liệu và kiến trúc để cùng đội ngũ xây dựng an toàn hơn.</p><div className="actions"><a className="button primary" href="https://github.com/itgisgroup/liocode"><Github size={18}/> Tải Liodev <ArrowRight size={16}/></a><a className="button ghost" href="https://zalo.me/0909099580">Trao đổi cùng ERPCloud</a></div><div className="proof"><span><Check size={15}/> Local-first</span><span><Check size={15}/> Open source</span><span><Check size={15}/> Sẵn sàng cho Odoo</span></div></div><div className="editor-window"><div className="window-bar"><span/><span/><span/><small>liodev · erpcloud_sale</small></div><div className="editor-body"><div className="line-numbers">01<br/>02<br/>03<br/>04<br/>05<br/>06<br/>07</div><pre><code><i>class</i> <b>SaleOrder</b>(models.Model):{`\n`}  _inherit = <u>"sale.order"</u>{`\n\n`}  <i>def</i> action_confirm(self):{`\n`}    <span className="cyan"># AI đã kiểm tra quyền và workflow</span>{`\n`}    <i>return</i> super().action_confirm()</code></pre><div className="agent-chip"><Bot size={15}/> Architect đã hiểu dependency</div></div></div></section>
      <section id="context" className="feature-section"><div className="section-intro"><span className="section-kicker">01 / NGỮ CẢNH</span><h2>Code cùng ngôn ngữ doanh nghiệp.</h2><p>Không chỉ hoàn thành câu lệnh. Liodev kết nối code với model, view, security, workflow và module dependency bạn đang vận hành.</p></div><div className="feature-list"><div><strong>01</strong><h3>Hiểu module Odoo</h3><p>Đi qua model, XML view, access rule và manifest như một kỹ sư ERP.</p></div><div><strong>02</strong><h3>Tìm kiếm xuyên codebase</h3><p>Truy vết nơi dữ liệu bắt đầu, biến đổi và được dùng trong quy trình.</p></div><div><strong>03</strong><h3>Giải thích theo nghiệp vụ</h3><p>Chuyển diff kỹ thuật thành tác động mà product owner có thể review.</p></div></div></section>
      <section id="agents" className="dark-section"><div className="section-intro"><span className="section-kicker">02 / AGENT MODES</span><h2>Một agent. Bốn cách ship code.</h2><p>Đổi ngữ cảnh mà không đổi công cụ. Mỗi mode có một vai trò rõ trong vòng đời phát triển ERP.</p></div><div className="agent-grid">{agents.map(([name, text, Icon]) => <article className="agent-card" key={name}><Icon size={22}/><h3>{name}</h3><p>{text}</p><ArrowRight size={17}/></article>)}</div></section>
      <section className="safety section-grid"><div><span className="section-kicker">03 / CONTROL</span><h2>An toàn cho hệ thống doanh nghiệp.</h2><p>AI có thể đề xuất nhanh. Đội ngũ vẫn giữ quyền quyết định cuối cùng với preview, audit và approval gate.</p></div><ul className="checks"><li><ShieldCheck/> Preview thay đổi trước khi áp dụng</li><li><ShieldCheck/> Audit intent và diff có thể truy vết</li><li><ShieldCheck/> Approval gate cho thao tác nhạy cảm</li><li><ShieldCheck/> Kiểm soát model, provider và dữ liệu</li></ul></section>
      <section id="open-source" className="open-section"><div className="open-card"><Github size={32}/><div><span className="section-kicker">04 / OPEN SOURCE</span><h2>Minh bạch từ nền tảng.</h2><p>Liodev được ERPCloud phát triển trên nền OpenCode fork. Source, license và roadmap được công khai để đội ngũ có thể kiểm tra, mở rộng và self-host.</p><a href="https://github.com/itgisgroup/liocode">Xem source trên GitHub <ArrowRight size={16}/></a></div></div></section>
      <section id="faq" className="faq"><div className="section-intro"><span className="section-kicker">05 / FAQ</span><h2>Bắt đầu từ câu hỏi đúng.</h2></div><div>{faqs.map((q, i) => <button className="faq-row" key={q} onClick={() => setOpen(open === i ? null : i)}><span>{q}</span>{open === i ? <X size={18}/> : <ChevronDown size={18}/>} {open === i && <p>Liodev được thiết kế cho codebase ERP thực tế, ưu tiên quyền kiểm soát, khả năng kiểm chứng và quy trình an toàn.</p>}</button>)}</div></section>
    </main><footer><div className="footer-brand"><img src="/brand/liodev-logo-light.svg" alt="Liodev"/><p>Code ERP. Ship with context.</p></div><div className="footer-links"><a href="https://github.com/itgisgroup/liocode">GitHub</a><a href="https://zalo.me/0909099580">Liên hệ ERPCloud</a><a href="mailto:info@erpcloud.vn">info@erpcloud.vn</a></div><small>© 2026 Liodev · Một sản phẩm của ERPCloud</small></footer>
  </div>
}
